# Generated by Django 5.2.4 on 2025-07-24 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameStore', '0002_order_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Product_item',
        ),
    ]
