# Generated by Django 5.2.4 on 2025-07-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameStore', '0005_order_customer_order_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='tags',
            field=models.ManyToManyField(to='GameStore.tag'),
        ),
    ]
