# Generated by Django 5.2.4 on 2025-07-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameStore', '0006_tag_order_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tags',
        ),
        migrations.AddField(
            model_name='product_item',
            name='tags',
            field=models.ManyToManyField(to='GameStore.tag'),
        ),
    ]
